name: Docker Push

on:
  push:
    branches: [ main ]
    
env:
  # github.repository as <account>/<repo>
  IMAGE_NAME: jnewbon/telegraf-smartctl

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ env.IMAGE_NAME }}:latest
    
    - name: Docker Login
      uses: docker/login-action@v1.10.0
      with:
        username: jnewbon
        password: ${{ secrets.DOCKER_TOKEN }}
        
    - name: Push to docker
      run: docker push ${{ env.IMAGE_NAME }}:latest
